name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3

      - name: Install package
        run: pipx install .

      - name: Check version
        run: |
          version=$(grep version src/diffused/__init__.py | cut -d'"' -f 2)
          set -e
          [[ $(diffused --version) == $version ]]
          [[ $(diffused -v) == $version ]]

      - name: Get help
        run: diffused --help

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arguments:
          - apple
          - apple --output apple.jpg --width=512 --height=512 --device=cpu --negative-prompt=blurry --guidance-scale=7.5
          - apple -o apple.png -W 256 -H 256 -d cpu -np dark -gs 7.5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface/
          key: ${{ runner.os }}-huggingface

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3

      - name: Install package
        run: pipx install .

      - name: Generate image
        run: diffused segmind/tiny-sd ${{ matrix.arguments }}
        env:
          DO_NOT_TRACK: 1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ hashFiles('**/*.jpg', '**/*.png') }}
          path: |
            *.jpg
            *.png
